[package]
name = "raytracer"
version = "0.1.0"
authors = ["hyeonjang <hyeonjang.an@skku.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rxmath = { path = "../rxmath" }
image = "0.23.8"
num-complex = "0.3.0"
