[package]
name = "rxmath"
version = "0.1.0"
authors = ["hyeonjang <hyeonjang.an@skku.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.12"
libc = "0.2.76"
rand = "0.7.3"
